package com.zugaldia.speedofsound.app.portals

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class TextUtilsTest {

    @Test
    fun `unicodeToKeySym and keySymToUnicode round-trip for plain English`() {
        val input = "Using my voice, I can type at the speed of sound."
        for (char in input) {
            val keySym = TextUtils.unicodeToKeySym(char.code)
            val roundTripped = TextUtils.keySymToUnicode(keySym)
            val codeHex = char.code.toString(16).uppercase()
            assertEquals(char.code, roundTripped, "Round-trip failed for '$char' (U+$codeHex)")
        }
    }

    // sample.txt contains Article 1 of the Universal Declaration of Human Rights in all six
    // official languages of the UN: English, French, Spanish, Russian, Arabic, and Chinese.
    // It is generated by the Makefile in this directory from the official UN website (un.org).
    private fun loadSample(): String {
        val resource = javaClass.classLoader.getResourceAsStream("sample.txt")
        assertNotNull(resource, "sample.txt not found in test resources")
        return resource.bufferedReader(Charsets.UTF_8).readText()
    }

    @Test
    fun `textToKeySym succeeds for plain English`() {
        val input = "Using my voice, I can type at the speed of sound."
        val result = TextUtils.textToKeySym(input, filterNoKeySym = false)
        assertTrue(result.isSuccess)
        assertEquals(input.length, result.getOrThrow().size)
    }

    @Test
    fun `textToKeySym succeeds for all languages in sample`() {
        val sample = loadSample()
        val result = TextUtils.textToKeySym(sample, filterNoKeySym = false)
        assertTrue(result.isSuccess)
        assertEquals(sample.length, result.getOrThrow().size)
    }

    @Test
    fun `unicodeToKeySym and keySymToUnicode round-trip for all characters in sample`() {
        val sample = loadSample()
        for (char in sample) {
            val keySym = TextUtils.unicodeToKeySym(char.code)
            val roundTripped = TextUtils.keySymToUnicode(keySym)
            val codeHex = char.code.toString(16).uppercase()
            assertEquals(char.code, roundTripped, "Round-trip failed for '$char' (U+$codeHex)")
        }
    }
}
