name: Snap Publish

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      channel:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 0.8.0 or 0.8.0-beta.1)'
        required: true
        type: string
      channel:
        description: 'Release channel'
        required: true
        type: choice
        options:
          - stable
          - beta

jobs:
  snap:
    name: "Snap"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
      - uses: snapcore/action-build@v1
        id: build
      - name: Lint snap
        run: snapcraft lint ${{ steps.build.outputs.snap }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ inputs.channel }}
