name: Snap Build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - 'scripts/**'
      - '**.md'
      - 'mkdocs.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - 'scripts/**'
      - '**.md'
      - 'mkdocs.yml'
jobs:
  snap:
    name: "Snap"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: snapcore/action-build@v1
        id: build
      - name: Lint snap
        run: sg lxd -c "snapcraft lint ${{ steps.build.outputs.snap }}"
